### ISSUE TITLE
申请适配 QQ飞车

### ISSUE THREAD

**Issue by CoconutOvO** [shadow3aaa/8gen3-offest-fas-rs-extension#1]
QQ飞车：com.tencent.tmgp.speedmobile
手机：小米14
Scene开启核心分配 没使用A-SOUL
60帧是局外 120帧是局内
Gpu有降压
![Screenshot_2024-07-25-08-46-45-346_com omarea vtools](https://github.com/user-attachments/assets/fe39e970-0c99-432d-8dea-76c98d7bee03)

**Comment by shadow3aaa** [comment]
适配要求统一线程放置，所以需要使用asopt
