### ISSUE TITLE
申请适配崩坏星穹铁道

### ISSUE THREAD

**Issue by ertutio** [shadow3aaa/8gen3-offest-fas-rs-extension#2]
包名：com.miHoYo.hkrpg
此帧率截图
![Screenshot_2024-07-25-10-03-58-67](https://github.com/user-attachments/assets/23ea0d22-97e4-4cbd-a09f-d6ebc806339c)
使用了 fas-rs 以及 asoul-opt

**Comment by shadow3aaa** [comment]
92c7aeed52da9922ff6909f06a4479549662dbaa
