### ISSUE TITLE
申请适配 蔚蓝档案

### ISSUE THREAD

**Issue by CoconutOvO** [shadow3aaa/8gen3-offest-fas-rs-extension#4]
蔚蓝档案：com.RoamingStar.BlueArchive
手机：小米14
Scene开启核心分配 没使用A-SOUL
Gpu有降压
![Screenshot_2024-07-25-15-56-45-194_com.omarea.vtools.jpg](https://github.com/user-attachments/assets/6379791c-2b6d-48af-8e62-342acd9bf23b)

**Comment by shadow3aaa** [comment]
需要保证放置统一性，不接受没使用asopt的
