### ISSUE TITLE
申请适配 逆水寒手游

### ISSUE THREAD

**Issue by Yuvzol0932** [shadow3aaa/8gen3-offest-fas-rs-extension#5]
设备:小米14pro
芯片8Gen3
游戏画质自定义全部拉满
使用了Asoul A.43 及fas-rs
未降压
com.netease.nshm

**Comment by Yuvzol0932** [comment]
![Screenshot_2024-07-25-16-15-06-536_com omarea vtools](https://github.com/user-attachments/assets/b3861655-6e0f-436e-afd3-4f36a8ce4850)

**Comment by shadow3aaa** [comment]
ea0534e1e757781057a7b569523fd19a52afe29d
