### ISSUE TITLE
申请适配 英雄联盟手游

### ISSUE THREAD

**Issue by JiangIce** [shadow3aaa/8gen3-offest-fas-rs-extension#7]
包名：com.tencent.lolm
![Screenshot_2024-07-31-00-11-04-481_com.omarea.vtools.jpg](https://github.com/user-attachments/assets/52a2e54c-534b-4253-9b26-e76d90d8189c)

**Comment by shadow3aaa** [comment]
2f05345934ecfdffdd177da74eec6b931858b6cd
