### ISSUE TITLE
申请适配 尘白禁区

### ISSUE THREAD

**Issue by JiangIce** [shadow3aaa/8gen3-offest-fas-rs-extension#8]
包名：com.dragonli.projectsnow.lhm
![Screenshot_2024-07-31-00-24-59-527_com.omarea.vtools.jpg](https://github.com/user-attachments/assets/015ac2cb-a171-429e-9def-80bb97fddfee)

**Comment by shadow3aaa** [comment]
看起来没什么好offset的
