### ISSUE TITLE
申请适配崩坏星穹铁道

### ISSUE THREAD

**Issue by ll772** [shadow3aaa/8gen3-offest-fas-rs-extension#9]
![Screenshot_2024-07-31-11-30-22-319_com omarea vtools](https://github.com/user-attachments/assets/f7ba5377-f3bb-430f-9232-66ad9e7703ea)
应用包名：com.miHoYo.hkrpg

**Comment by shadow3aaa** [comment]
92c7aeed52da9922ff6909f06a4479549662dbaa
